"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider } from 'next-auth/react';
// import { getServerSession } from "next-auth";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const session = getServerSession();

  return (
    <html lang="en">
       <body className={inter.className}>
          <SessionProvider >
              {children}
          </SessionProvider>
        </body>
    </html>
  );
}
